# Generated by Django 2.1.4 on 2018-12-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0002_lab_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='lab',
            name='detailed_description',
            field=models.TextField(blank=True),
        ),
    ]
