# Generated by Django 2.1.4 on 2018-12-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0003_auto_20181210_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
